import { error } from '@sveltejs/kit';
import { BYPASS_TOKEN } from '$env/static/private';

export const load = async ({ params }) => {
  // No dynamic CMS-backed pages are served from this catch-all anymore.
  // Anything that lands here is an unknown URL (e.g. legacy WordPress paths
  // still in Google's index) — return 404 so it drops out of search results.
  throw error(404, `No page found for /${params.path}`);
};

// Use a 32+ character fallback if BYPASS_TOKEN is not set (during build)
const getBypassToken = () => {
  if (BYPASS_TOKEN && BYPASS_TOKEN.length >= 32) {
    return BYPASS_TOKEN;
  }
  // Fallback for build time when env var may not be available
  return '9b47deddf389b647b67158a19fe1013281fd3e7a4086a1c1e4a513b79c051e9f';
};

export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 60,

    // Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
    // with a __prerender_bypass=<token> cookie.
    //
    // Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.
    bypassToken: getBypassToken(),

    // List of valid query parameters. Other parameters (such as utm tracking codes) will be ignored,
    // ensuring that they do not result in content being regenerated unnecessarily
    allowQuery: ['t', 'drawer']
  }
};
