import { error } from '@sveltejs/kit';
import { fetchPage } from '$lib/content';
import { BYPASS_TOKEN } from '$env/static/private';

export const load = async ({ params, locals, fetch, url }) => {
  const version = locals.version;
  // don't catch paths that end with an extension
  if (/\..+$/.test(params.path)) throw error(404);

  const page = await fetchPage({
    slug: params.path,
    version,
    fetch,
    url
  });

  return { page };
};

// Use a 32+ character fallback if BYPASS_TOKEN is not set (during build)
const getBypassToken = () => {
  if (BYPASS_TOKEN && BYPASS_TOKEN.length >= 32) {
    return BYPASS_TOKEN;
  }
  // Fallback for build time when env var may not be available
  return '9b47deddf389b647b67158a19fe1013281fd3e7a4086a1c1e4a513b79c051e9f';
};

export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 60,

    // Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
    // with a __prerender_bypass=<token> cookie.
    //
    // Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.
    bypassToken: getBypassToken(),

    // List of valid query parameters. Other parameters (such as utm tracking codes) will be ignored,
    // ensuring that they do not result in content being regenerated unnecessarily
    allowQuery: ['t', 'drawer']
  }
};
